CREATE DATABASE banco_enem;
USE bd_enem;
CREATE TABLE microdados (
    NU_INSCRICAO VARCHAR(12), 
    NU_ANO INT,
    TP_FAIXA_ETARIA INT,
    TP_SEXO VARCHAR(1),
    TP_ESTADO_CIVIL CHAR(1),
    TP_COR_RACA CHAR(1),
    TP_NACIONALIDADE CHAR(1),
    TP_ST_CONCLUSAO CHAR(1),
    TP_ANO_CONCLUIU INT,
    TP_ESCOLA CHAR(1),
    TP_ENSINO CHAR(1),
    IN_TREINEIRO CHAR(1),
    CO_MUNICIPIO_ESC VARCHAR(7),
    NO_MUNICIPIO_ESC VARCHAR(150),
    CO_UF_ESC CHAR(2),
    SG_UF_ESC CHAR(2),
    TP_DEPENDENCIA_ADM_ESC CHAR(1),
    TP_LOCALIZACAO_ESC CHAR(2),
    TP_SIT_FUNC_ESC CHAR(1),
    CO_MUNICIPIO_PROVA VARCHAR(7),
    NO_MUNICIPIO_PROVA VARCHAR(150),
    CO_UF_PROVA VARCHAR(2),
    SG_UF_PROVA VARCHAR(2),
    TP_PRESENCA_CN CHAR(1),
    TP_PRESENCA_CH CHAR(1),
    TP_PRESENCA_LC CHAR(1),
    TP_PRESENCA_MT CHAR(1),
    CO_PROVA_CN CHAR(4),
    CO_PROVA_CH CHAR(4),
    CO_PROVA_LC CHAR(4),
    CO_PROVA_MT CHAR(4),
    NU_NOTA_CN CHAR(6),
    NU_NOTA_CH CHAR(6),
    NU_NOTA_LC CHAR(6),
    NU_NOTA_MT CHAR(6),
    TX_RESPOSTAS_CN VARCHAR(45),
    TX_RESPOSTAS_CH VARCHAR(45),
    TX_RESPOSTAS_LC VARCHAR(45),
    TX_RESPOSTAS_MT VARCHAR(45),
    TP_LINGUA CHAR(1),
    TX_GABARITO_CN VARCHAR(45),
    TX_GABARITO_CH VARCHAR(45),
    TX_GABARITO_LC VARCHAR(50),
    TX_GABARITO_MT VARCHAR(45),
    TP_STATUS_REDACAO CHAR(1),
    NU_NOTA_COMP1 CHAR(3),
    NU_NOTA_COMP2 CHAR(3),
    NU_NOTA_COMP3 CHAR(3),
    NU_NOTA_COMP4 CHAR(3),
    NU_NOTA_COMP5 CHAR(3),
    NU_NOTA_REDACAO CHAR(4),
    Q001 CHAR(1),
    Q002 CHAR(1),
    Q003 CHAR(1),
    Q004 CHAR(1),
    Q005 CHAR(2),
    Q006 CHAR(1),
    Q007 CHAR(1),
    Q008 CHAR(1),
    Q009 CHAR(1),
    Q010 CHAR(1),
    Q011 CHAR(1),
    Q012 CHAR(1),
    Q013 CHAR(1),
    Q014 CHAR(1),
    Q015 CHAR(1),
    Q016 CHAR(1),
    Q017 CHAR(1),
    Q018 CHAR(1),
    Q019 CHAR(1),
    Q020 CHAR(1),
    Q021 CHAR(1),
    Q022 CHAR(1),
    Q023 CHAR(1),
    Q024 CHAR(1),
    Q025 CHAR(1)
);

LOAD DATA INFILE "C:/Users/Tomat/Downloads/microdados_enem_2022/DADOS/MICRODADOS_ENEM_2022.csv" 
INTO TABLE microdados 
CHARACTER SET latin1
FIELDS TERMINATED BY ';' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

CREATE TABLE ESCOLA(
    CO_MUNICIPIO VARCHAR(20) PRIMARY KEY,
	NO_MUNICIPIO VARCHAR(150),
    CO_UF INTEGER,
    SG_UF VARCHAR(2),
    TP_DEP_ADM INTEGER,
    TP_LOC INTEGER,
    TP_SIT_F INTEGER
);

CREATE TABLE PARTICIPANTE(
	NU_INSCRICAO VARCHAR(12) PRIMARY KEY,
    NU_ANO INTEGER NOT NULL,
    FAIXA_ETARIA INTEGER,
    SEXO CHAR(1),
    ESTADO_CIVIL INTEGER,
    COR_RACA INTEGER,
    NACIONALIDADE INTEGER,
    COD_ESCOLA VARCHAR(20),
    TP_CONCLUSAO INTEGER,
    TP_CONCLUIU INTEGER,
    TP_ESCOLA INTEGER,
    TP_ENSINO INTEGER,
    IN_TREINEIRO INTEGER,
    LOCAL_PROVA VARCHAR(20),
    FOREIGN KEY (COD_ESCOLA) REFERENCES ESCOLA(CO_MUNICIPIO),
    FOREIGN KEY (LOCAL_PROVA) REFERENCES LOCAL_PROVA(CO_MUNICIPIO)
);

CREATE TABLE LOCAL_PROVA(
	CO_MUNICIPIO VARCHAR(20),
    NO_MUNICIPIO VARCHAR(150),
    CO_UF VARCHAR(2),
    SG_UF VARCHAR(2)
);

CREATE TABLE PROVA_OBJ(
	NU_ALUNO VARCHAR(15) PRIMARY KEY,
    TP_PRESENCA_CN INTEGER,
    TP_PRESENCA_CH INTEGER,
    TP_PRESENCA_LC INTEGER,
    TP_PRESENCA_MT INTEGER,
    CO_PROVA_CN INTEGER,
	CO_PROVA_CH INTEGER,
	CO_PROVA_LC INTEGER,
	CO_PROVA_MT INTEGER,
	NU_NOTA_CN INTEGER,
	NU_NOTA_CH INTEGER,
	NU_NOTA_LC INTEGER,
	NU_NOTA_MT INTEGER,
	TX_RESPOSTAS_CN VARCHAR(45),
	TX_RESPOSTAS_CH VARCHAR(45),
	TX_RESPOSTAS_LC VARCHAR(45),
	TX_RESPOSTAS_MT VARCHAR(45),
	TP_LINGUA INTEGER,
	FOREIGN KEY (NU_ALUNO) REFERENCES PARTICIPANTE(NU_INSCRICAO)
);
CREATE TABLE TIPO_PROVA(
	T_PROVA_CN BIGINT,
	GABARITO_CN VARCHAR(50),
    T_PROVA_CH BIGINT,
	GABARITO_CH VARCHAR(50),
    T_PROVA_LC BIGINT,
	GABARITO_LC VARCHAR(50),
    T_PROVA_MT BIGINT,
    GABARITO_MT VARCHAR(50)
);
CREATE TABLE REDACAO(
	NU_ALUNO VARCHAR(15) PRIMARY KEY,
    TP_STATUS INTEGER,
    NOTA_C1 INTEGER,
    NOTA_C2 INTEGER,
    NOTA_C3 INTEGER,
    NOTA_C4 INTEGER,
    NOTA_C5 INTEGER,
	NOTA_R INTEGER,
    FOREIGN KEY (NU_ALUNO) REFERENCES PARTICIPANTE(NU_INSCRICAO)
);

CREATE TABLE QUEST_SOCIO(
	NU_ALUNO VARCHAR(15) PRIMARY KEY,
    Q001 VARCHAR(1),
    Q002 VARCHAR(1),
    Q003 VARCHAR(1),
    Q004 VARCHAR(1),
    Q005 VARCHAR(1),
    Q006 VARCHAR(1),
    Q007 VARCHAR(1),
    Q008 VARCHAR(1),
    Q009 VARCHAR(1),
    Q010 VARCHAR(1),
    Q011 VARCHAR(1),
    Q012 VARCHAR(1),
    Q013 VARCHAR(1),
    Q014 VARCHAR(1),
    Q015 VARCHAR(1),
    Q016 VARCHAR(1),
    Q017 VARCHAR(1),
    Q018 VARCHAR(1),
    Q019 VARCHAR(1),
    Q020 VARCHAR(1),
    Q021 VARCHAR(1),
    Q022 VARCHAR(1),
    Q023 VARCHAR(1),
    Q024 VARCHAR(1),
    Q025 VARCHAR(1),
    FOREIGN KEY (NU_ALUNO) REFERENCES PARTICIPANTE(NU_INSCRICAO)
);
INSERT INTO ESCOLA(CO_MUNICIPIO, NO_MUNICIPIO, CO_UF, SG_UF, TP_DEP_ADM, TP_LOC, TP_SIT_F) SELECT co_municipio_esc, no_municipio_esc, co_uf_esc, sg_uf_esc, tp_dependencia_adm_esc, tp_localizacao_esc, tp_sit_func_esc FROM microdados;
INSERT INTO PARTICIPANTE(NU_INSCRICAO, NU_ANO, FAIXA_ETARIA, SEXO, ESTADO_CIVIL, COR_RACA, NACIONALIDADE, COD_ESCOLA, TP_CONCLUSAO, TP_CONCLUIU, TP_ESCOLA, TP_ENSINO, IN_TREINEIRO, LOCAL_PROVA) SELECT nu_inscricao, nu_ano, tp_faixa_etaria, tp_sexo, tp_estado_civil, tp_cor_raca, tp_nacionalidade, co_municipio_esc, tp_st_conclusao, tp_ano_concluiu, tp_escola, tp_ensino, in_treineiro, co_municipio_prova FROM microdados;
INSERT INTO local_prova(CO_MUNICIPIO, NO_MUNICIPIO, CO_UF, SG_UF) SELECT CO_MUNICIPIO_PROVA, NO_MUNICIPIO_PROVA, CO_UF_PROVA, SG_UF_PROVA FROM microdados;
INSERT INTO PROVA_OBJ(NU_ALUNO, TP_PRESENCA_CN, TP_PRESENCA_CH, TP_PRESENCA_LC, TP_PRESENCA_MT, CO_PROVA_CN, CO_PROVA_CH, CO_PROVA_LC, CO_PROVA_MT, NU_NOTA_CN, NU_NOTA_CH, NU_NOTA_LC, NU_NOTA_MT, 
	TX_RESPOSTAS_CN, TX_RESPOSTAS_CH, TX_RESPOSTAS_LC, TX_RESPOSTAS_MT, TP_LINGUA) SELECT NU_INSCRICAO, TP_PRESENCA_CN, TP_PRESENCA_CH, TP_PRESENCA_LC, TP_PRESENCA_MT, CO_PROVA_CN, CO_PROVA_CH,
	CO_PROVA_LC, CO_PROVA_MT, NU_NOTA_CN, NU_NOTA_CH, NU_NOTA_LC, NU_NOTA_MT, TX_RESPOSTAS_CN, TX_RESPOSTAS_CH, TX_RESPOSTAS_LC, TX_RESPOSTAS_MT, TP_LINGUA FROM microdados;
INSERT INTO TIPO_PROVA(T_PROVA_CN, GABARITO_CN, T_PROVA_CH, GABARITO_CH, T_PROVA_LC, GABARITO_LC, T_PROVA_MT, GABARITO_MT) SELECT CO_PROVA_CN, TX_GABARITO_CN, CO_PROVA_CH, TX_GABARITO_CH, CO_PROVA_LC, TX_GABARITO_LC, CO_PROVA_MT, TX_GABARITO_MT FROM microdados;
DELETE FROM TIPO_PROVA
WHERE (T_PROVA_CN, GABARITO_CN, T_PROVA_CH, GABARITO_CH, T_PROVA_LC, GABARITO_LC, T_PROVA_MT, GABARITO_MT) IN (
    SELECT T_PROVA_CN, GABARITO_CN, T_PROVA_CH, GABARITO_CH, T_PROVA_LC, GABARITO_LC, T_PROVA_MT, GABARITO_MT
    FROM (
        SELECT T_PROVA_CN, GABARITO_CN, T_PROVA_CH, GABARITO_CH, T_PROVA_LC, GABARITO_LC, T_PROVA_MT, GABARITO_MT,
               ROW_NUMBER() OVER (
                   PARTITION BY T_PROVA_CN, GABARITO_CN, T_PROVA_CH, GABARITO_CH, T_PROVA_LC, GABARITO_LC, T_PROVA_MT, GABARITO_MT
                   ORDER BY (SELECT NULL)
               ) AS rn
        FROM TIPO_PROVA
    ) AS sub
    WHERE rn > 1
);
INSERT INTO REDACAO(NU_ALUNO, TP_STATUS, NOTA_C1, NOTA_C2, NOTA_C3, NOTA_C4, NOTA_C5, NOTA_R) SELECT NU_INSCRICAO, TP_STATUS_REDACAO, NU_NOTA_COMP1, NU_NOTA_COMP2, NU_NOTA_COMP3, NU_NOTA_COMP4, NU_NOTA_COMP5, NU_NOTA_REDACAO FROM microdados;
INSERT INTO QUEST_SOCIO(NU_ALUNO, Q001, Q002, Q003, Q004, Q005, Q006, Q007, Q008, Q009, Q010, Q011, Q012, Q013, Q014, Q015, Q016, Q017, Q018, Q019, Q020, Q021, Q022, Q023, Q024, Q025) SELECT NU_INSCRICAO, Q001, Q002, Q003, Q004, Q005, Q006, Q007, Q008, Q009, Q010, Q011, Q012, Q013, Q014, Q015, Q016, Q017, Q018, Q019, Q020, Q021, Q022, Q023, Q024, Q025 FROM microdados;

SELECT COUNT(*) FROM PARTICIPANTE WHERE SEXO="F" AND COR_RACA=2 OR COR_RACA=3;

SELECT ESCOLA.SG_UF AS Estado,
AVG((PROVA_OBJ.NU_NOTA_CN + PROVA_OBJ.NU_NOTA_CH + PROVA_OBJ.NU_NOTA_LC + PROVA_OBJ.NU_NOTA_MT + REDACAO.NOTA_R) / 5) AS Media
FROM PARTICIPANTE
INNER JOIN ESCOLA ON PARTICIPANTE.COD_ESCOLA = ESCOLA.CO_MUNICIPIO
INNER JOIN PROVA_OBJ ON PARTICIPANTE.NU_INSCRICAO = PROVA_OBJ.NU_ALUNO
INNER JOIN REDACAO ON PARTICIPANTE.NU_INSCRICAO = REDACAO.NU_ALUNO
WHERE PARTICIPANTE.SEXO = 'F' AND (PARTICIPANTE.COR_RACA = 2 OR PARTICIPANTE.COR_RACA = 3)
GROUP BY ESCOLA.SG_UF;





